// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1pmDmZFeSPnwM3jESVSYsabYiCGSCjDY',
    appId: '1:939355456574:web:9f842abaa1eebe900a7d6f',
    messagingSenderId: '939355456574',
    projectId: 'intern1-f40dd',
    authDomain: 'intern1-f40dd.firebaseapp.com',
    storageBucket: 'intern1-f40dd.firebasestorage.app',
    measurementId: 'G-MFWZ9T50YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpbiiRvaTif1tJio7wAa2jGtoZQjBrr8',
    appId: '1:939355456574:android:a7fdacfaf4cc46170a7d6f',
    messagingSenderId: '939355456574',
    projectId: 'intern1-f40dd',
    storageBucket: 'intern1-f40dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvS8F4Fo3uUD9dX6O-nIYqJGrWHYLcVA',
    appId: '1:939355456574:ios:99eb470dbbac72aa0a7d6f',
    messagingSenderId: '939355456574',
    projectId: 'intern1-f40dd',
    storageBucket: 'intern1-f40dd.firebasestorage.app',
    iosBundleId: 'com.example.intern1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvS8F4Fo3uUD9dX6O-nIYqJGrWHYLcVA',
    appId: '1:939355456574:ios:99eb470dbbac72aa0a7d6f',
    messagingSenderId: '939355456574',
    projectId: 'intern1-f40dd',
    storageBucket: 'intern1-f40dd.firebasestorage.app',
    iosBundleId: 'com.example.intern1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1pmDmZFeSPnwM3jESVSYsabYiCGSCjDY',
    appId: '1:939355456574:web:cee80b7bf0fb827a0a7d6f',
    messagingSenderId: '939355456574',
    projectId: 'intern1-f40dd',
    authDomain: 'intern1-f40dd.firebaseapp.com',
    storageBucket: 'intern1-f40dd.firebasestorage.app',
    measurementId: 'G-LXPHQE2BRD',
  );
}
